### ISSUE TITLE
Release last non schooldriver release

### ISSUE THREAD

**Issue by bufke** [burke-software/django-sis#210]
Next release after this will be 1.0 and we'll start pushing stable versions! Schooldriver will be the new name. Releases will be posted as github issues. No other changes, will still be open source forever.

Release manager is @qdonnellan 

- [x] Merge develop to master
- [x] Ensure Travis CI passes
- [x] Deploy to staging server
- [x] Get @bufke to approve
- [x] Make announcement on G+
- [x] Deploy to internal BSC servers

**Comment by qdonnellan** [comment]
I'm merging locally right now and then I'll push

**Comment by qdonnellan** [comment]
Merged.... all fixes related to this release should go on master now

**Comment by qdonnellan** [comment]
Travis is green for the first time in...
