### ISSUE TITLE
Best way to integrate with existing project

### ISSUE THREAD

**Issue by gustavo-gomez** [burke-software/django-sis#211]
Hi, we are trying to use django-sis in an existing Django project. What is the best way to do it? We don't want to modify django-sis, just use it as a third-party library.

Thanks.

**Comment by bufke** [comment]
What are you looking to do? I could probably answer better if I had a general idea of what  you aim to achieve. 

django-sis is a large project with many, many apps. In theory you could add what you want but changes could break things - for example I assume postgres is being using. We're hoping to do a stable release and name change soon - perhaps a month. I won't break things without notifying people after this.

**Comment by gustavo-gomez** [comment]
Thanks for your response.

We are creating a new Django project and we have a custom application with some models. We want to "merge" django-sis with our project to integrate both functionality. Is it the best way to just include this application on settings_local.py, as we don't want to change django-sis source?

**Comment by bufke** [comment]
We do a lot of work with people wanting custom applications - have you considering working with us upstream?

Which project do you think is bigger/more complex? If you are just adding a application app to django-sis I would say when you deploy django-sis as is and edit settings_local to reference your app (adding INSTALLED_APPS, ect). 

I'm thinking of ways to make it easier for people to run this and integrate with it. I'm really open to any ideas. I was thinking of just doing an official docker hub image so people can avoid complexity. I could put it on pypi but so much of the project is in settings and such that it seems hard to just add some django_sis app to your project and run - but I'd consider it.

Here's our new work in progress docs page - http://docs.schooldriver.org you can guess the new name.
