### ISSUE TITLE
Custom administration page

### ISSUE THREAD

**Issue by wlwzrd** [burke-software/django-sis#212]
Hi,
I'm triying to modify the default administration page in order to add some extra models. I have some models to extend the functionality, so in this way I have on my test/admin.py file : 

from test.models import Subject

class SubjectAdmin(admin.ModelAdmin)
       ....
admin.site.register(Subject,SubjectAdmin)

Of course the app is in the INSTALLED_APPS variable. What do I need to do to have application models listed in the administration page. 

Thanks!

**Comment by bufke** [comment]
We are using this http://django-grappelli.readthedocs.org/en/latest/dashboard_setup.html See https://github.com/burke-software/django-sis/blob/master/ecwsp/dashboard.py

Reopen if I haven't answered your question.
